### ISSUE TITLE
Tooltip issues

### ISSUE THREAD

**Issue by ilyabrower** [semrush/intergalactic#942]
**Expected behavior**

- [ ] VoiceOver reads tooltip content only one time

- [X] if the tooltip contains a link and we move focus on popper or this link, then to hide the tooltip, we need to press Escape once (for now - twice).
- [x] Working disabled (types and aria-*) instead of interaction `none`

**Todo**

- [ ] remove aria-describedby from tooltip and add it to every website example

**Comment by Peoplecanfly1** [comment]
Please take into consideration that if its Icon components voice over repeat not twice but 4 times!  
Thred in [slack](https://semrush.slack.com/archives/C293ALLQ2/p1705925439684049).

**Comment by msereniti** [comment]
Fixed in https://github.com/semrush/intergalactic/pull/1094
